version: "3"
services:
  nginx:
    image: php_nginx:latest
    container_name: php_nginx
    build:
      context: ./nginx
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 384M
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
      - postgres
      - mailcatcher
    volumes:
      - /var/www/php_php:/var/www/php

  php:
    image: php_php:latest
    container_name: php_php
    build:
      context: ./php
    deploy:
      resources:
        limits:
          memory: 3072M
        reservations:
          memory: 2944M
    ports:
      - "19000:9000"
      - "19009:9009"
      - "12000:22"
    links:
      - postgres
      - rabbitmq
    volumes:
      - /var/www/php_php:/var/www/php
    environment:
      - HOSTNAME
      - RABBITMQ_USER=rabbitmq
      - RABBITMQ_PASSWORD=rabbitmq
      - RABBITMQ_HOST=rabbitmq

  postgres:
    build:
      context: ./postgres
      dockerfile: postgres.dockerfile
    image: php_postgres
    container_name: php_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      PGDATA: /var/lib/php_postgres/data
    volumes:
      - dbapp:/var/lib/php_postgres/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  mailcatcher:
    image: php_mailcatcher:latest
    container_name: php_mailcatcher
    build:
      context: ./mailcatcher
    deploy:
      resources:
        limits:
          memory: 64M
        reservations:
          memory: 48M
    ports:
      - "1080:1080"

  rabbitmq:
    image: php_rabbitmq:latest
    container_name: php_rabbitmq
    build:
      context: ./rabbitmq
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=rabbitmq
      - RABBITMQ_DEFAULT_PASS=rabbitmq
volumes:
  dbapp:
    external: true